# Generated by Django 4.2.4 on 2023-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(default=0)),
                ('level_type', models.IntegerField(default=0)),
                ('question', models.IntegerField(default=0)),
                ('option', models.IntegerField(default=0)),
                ('question_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
